# Generated by Django 5.1.3 on 2024-12-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_service_description_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackages',
            name='package_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
