# Generated by Django 5.1.3 on 2024-12-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servicepackages_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackages',
            name='image',
            field=models.ImageField(default=1, upload_to='service_images'),
            preserve_default=False,
        ),
    ]
