# Generated by Django 5.1.3 on 2024-12-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicepackages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackages',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_images'),
            preserve_default=False,
        ),
    ]
