# Generated by Django 5.1.3 on 2024-12-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_servicepackages_image_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
