# Generated by Django 5.1.3 on 2024-12-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_servicepackages_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackages',
            name='lkr_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
