# Generated by Django 5.1.3 on 2024-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='group',
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the tag', null=True, upload_to='tag_images/'),
        ),
    ]
